include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    omit_local_variable_types: ignore
  exclude:
    - "**/*.g.dart"
    - lib/l10n/app_localizations.dart
    - lib/l10n/app_localizations_*.dart

linter:
  rules:
    public_member_api_docs: false
