// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:what_2_eat/features/favorites/data/models/cached_favorite_list.dart';
import 'package:what_2_eat/features/recipes/data/models/cached_recipe_list.dart';
import 'package:what_2_eat/shared/domain/entities/favorite.dart';
import 'package:what_2_eat/shared/domain/entities/ingredient.dart';
import 'package:what_2_eat/shared/domain/entities/recipe.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedFavoriteListAdapter());
    registerAdapter(CachedRecipeListAdapter());
    registerAdapter(FavoriteAdapter());
    registerAdapter(IngredientAdapter());
    registerAdapter(RecipeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedFavoriteListAdapter());
    registerAdapter(CachedRecipeListAdapter());
    registerAdapter(FavoriteAdapter());
    registerAdapter(IngredientAdapter());
    registerAdapter(RecipeAdapter());
  }
}
